=== CheukBinLi/MC/编译好的包/Mc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Context (InitSystemClassLoader*,Bean*,Intercept*,ScanToPack*)>
<!--<!ELEMENT Context (CachePool,Bean*,Intercept*,ScanToPack*)>-->
<!ELEMENT CachePool EMPTY>
<!ELEMENT Bean EMPTY>
<!ELEMENT Intercept EMPTY>
<!ELEMENT ScanToPack EMPTY>
<!ELEMENT InitSystemClassLoader EMPTY>

<!--CachePool-->
<!--<!ATTLIST CachePool class (com.ben.mc.cache.DefaultCachePoolFactory) #REQUIRED>-->
<!--<!ATTLIST CachePool signleNewInstanceMethod (newInstance) #IMPLIED>-->

<!--Intercept-->
<!ATTLIST Intercept name CDATA #REQUIRED>
<!ATTLIST Intercept class CDATA #REQUIRED>
<!ATTLIST Intercept ref CDATA #REQUIRED>
<!ATTLIST Intercept methods CDATA "all">

<!--Bean-->
<!ATTLIST Bean name CDATA #REQUIRED>
<!ATTLIST Bean class CDATA #REQUIRED>
<!ATTLIST Bean type (class|field) #REQUIRED>
<!ATTLIST Bean ref CDATA #IMPLIED>

<!--ScanToPack-->
<!ATTLIST ScanToPack value CDATA #REQUIRED>
<!--ScanToPack-->
<!ATTLIST InitSystemClassLoader value (true|false) #REQUIRED>

=== CheukBinLi/MC/编译好的包/bean.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE Context SYSTEM "file:///E:/javaProject/Eclipse/MC/mc-util/src/main/java/Mc.dtd"> -->
<!DOCTYPE Context SYSTEM "Mc.dtd">
<Context>
	<InitSystemClassLoader value="true" /><!-- 引导加载失败时，设置true,把class载加到系统引导 -->

	<!-- 声名一个需要注入的对象 -->
	<Bean name="autoLoadTestImpl" class="com.ben.mc.AnthingTest.mc.xml.XmlIocTest1" type="field" ref="xxxxxxxxxxx110" />
	<!-- 注入声名 -->
	<Bean name="xxxxxxxxxxx110" class="com.ben.mc.AnthingTest.mc.xml.XmlAutoLoadTestImpl" type="class" />

	<!-- 注入 声名 -->
	<Bean name="xml1" class="com.ben.mc.AnthingTest.mc.xml.XmlIocTest1" type="class" />
	<Bean name="xml2" class="com.ben.mc.AnthingTest.mc.xml.XmlIocTest2" type="class" />
	<Bean name="xml3" class="com.ben.mc.AnthingTest.mc.xml.XmlIocTest3" type="class" />

	<!-- 拦截器 methods="all" 默认 -->
	<Intercept methods="aaxx2,aaxx3" class="com.ben.mc.AnthingTest.mc.xml.XmlIocTest1" name="intercept0083" ref="com.ben.mc.AnthingTest.mc.xml.DefaultInterceptionXml" />

	<!-- 自动扫描 -->
	<ScanToPack value="org.ben.mc.AnthingTest,com.**.AnthingTest" />
</Context>
